(ql:quickload "swank")
(ql:quickload "nibbles")
(ql:quickload "FLEXI-STREAMS")
(defvar buf (make-array 4 :element-type 'character))
(read-sequence buf *standard-input*)
(defvar result (nibbles:ub32ref/be (coerce (string-to-octets buf) '(vector (unsigned-byte 8))) 0))
(swank:create-server)
